### ISSUE TITLE
VWS crash: panicked at 'index out of bounds: the len is 4 but the index is 4'

### ISSUE THREAD

**Issue by ctrlcctrlv** [MFEK/glif#126]
82bf6a53d973c53f26d1dc0d70349d6e727b0e26

# File
```xml
<?xml version="1.0" encoding="UTF-8"?>
<glyph format="2" name="M">
  <advance width="1085" />
  <unicode hex="4d" />
  <outline>
    <contour>
      <point x="125.285736" type="curve" y="197.28552" />
      <point x="119.285736" y="262.28564" />
      <point x="115.285736" y="314.2854" />
      <point x="233.28574" y="324.2854" type="curve" />
      <point y="334.2854" x="351.28564" />
      <point y="289.28528" x="346.28574" />
      <point y="174.28549" type="curve" x="342.28577" />
      <point y="59.285492" x="338.28577" />
      <point x="324.2859" y="65.285645" />
      <point x="224.28574" type="curve" y="54.285645" />
      <point y="43.285645" x="124.285736" />
      <point y="132.28552" x="131.28574" />
    </contour>
    <contour>
      <point y="387" type="line" x="68" />
      <point type="line" x="479" y="387" />
      <point x="479" y="9" type="line" />
      <point x="68" y="9" type="line" />
    </contour>
  </outline>
  <!-- !!MFEK!!{
  "layers": [
    {
      "name": "Layer 0",
      "visible": true,
      "color": null,
      "outline": [
        {
          "inner": [
            {
              "x": 125.285736,
              "y": 197.28552,
              "a": {
                "At": [
                  119.285736,
                  262.28564
                ]
              },
              "b": {
                "At": [
                  131.28574,
                  132.28552
                ]
              },
              "name": null,
              "ptype": "Curve",
              "data": null
            },
            {
              "x": 233.28574,
              "y": 324.2854,
              "a": {
                "At": [
                  351.28564,
                  334.2854
                ]
              },
              "b": {
                "At": [
                  115.285736,
                  314.2854
                ]
              },
              "name": null,
              "ptype": "Curve",
              "data": null
            },
            {
              "x": 342.28577,
              "y": 174.28549,
              "a": {
                "At": [
                  338.28577,
                  59.285492
                ]
              },
              "b": {
                "At": [
                  346.28574,
                  289.28528
                ]
              },
              "name": null,
              "ptype": "Curve",
              "data": null
            },
            {
              "x": 224.28574,
              "y": 54.285645,
              "a": {
                "At": [
                  124.285736,
                  43.285645
                ]
              },
              "b": {
                "At": [
                  324.2859,
                  65.285645
                ]
              },
              "name": null,
              "ptype": "Curve",
              "data": null
            }
          ],
          "operation": {
            "VariableWidthStroke": {
              "data": {
                "handles": [
                  {
                    "left_offset": 10.0,
                    "right_offset": 10.0,
                    "tangent_offset": 0.0,
                    "interpolation": "Linear"
                  },
                  {
                    "left_offset": 10.0,
                    "right_offset": 10.0,
                    "tangent_offset": 0.0,
                    "interpolation": "Linear"
                  },
                  {
                    "left_offset": 40.25149507653363,
                    "right_offset": 40.25149507653363,
                    "tangent_offset": -1.685716592159115,
                    "interpolation": "Linear"
                  },
                  {
                    "left_offset": 10.0,
                    "right_offset": 10.0,
                    "tangent_offset": 0.0,
                    "interpolation": "Linear"
                  },
                  {
                    "left_offset": 10.0,
                    "right_offset": 10.0,
                    "tangent_offset": 0.0,
                    "interpolation": "Linear"
                  }
                ],
                "join_type": "Round",
                "cap_start_type": "Round",
                "cap_end_type": "Round",
                "remove_internal": false,
                "remove_external": false
              }
            }
          }
        },
        {
          "inner": [
            {
              "x": 68.0,
              "y": 387.0,
              "a": "Colocated",
              "b": "Colocated",
              "name": null,
              "ptype": "Line",
              "data": null
            },
            {
              "x": 479.0,
              "y": 387.0,
              "a": "Colocated",
              "b": "Colocated",
              "name": null,
              "ptype": "Line",
              "data": null
            },
            {
              "x": 479.0,
              "y": 9.0,
              "a": "Colocated",
              "b": "Colocated",
              "name": null,
              "ptype": "Line",
              "data": null
            },
            {
              "x": 68.0,
              "y": 9.0,
              "a": "Colocated",
              "b": "Colocated",
              "name": null,
              "ptype": "Line",
              "data": null
            }
          ],
          "operation": null
        }
      ],
      "operation": null,
      "images": []
    }
  ],
  "history": [],
  "order": "Cubic",
  "anchors": [],
  "components": {
    "root": "M",
    "vec": []
  },
  "flattened": null,
  "component_rects": null,
  "guidelines": [],
  "width": 1085,
  "unicode": [
    "M"
  ],
  "name": "M",
  "note": null,
  "format": 2,
  "filename": "/tmp/vws_rev.glif"
} -->
</glyph>
```

# Reproduction
1. Select the square by double clicking one of its points
    ![image](https://user-images.githubusercontent.com/838783/121252788-68825480-c876-11eb-843d-98fe9dfd7efa.png)
2. Press <kbd>Backspace</kbd>

# Crash
```
panicked at 'index out of bounds: the len is 4 but the index is 4', /home/fred/.cargo/git/checkouts/math.rlib-d2c76c88b18fa5ee/2547be6/src/variable_width_stroking.rs:138:28

Requested backtrace:
   0: MFEKglif::util::set_panic_hook::{{closure}}
             at src/util/mod.rs:61:26
   1: std::panicking::rust_panic_with_hook
             at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/panicking.rs:595:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/panicking.rs:497:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/panicking.rs:493:5
   5: core::panicking::panic_fmt
             at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/core/src/panicking.rs:92:14
   6: core::panicking::panic_bounds_check
             at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/core/src/panicking.rs:69:5
   7: <usize as core::slice::index::SliceIndex<[T]>>::index
             at /home/fred/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:184:10
   8: core::slice::index::<impl core::ops::index::Index<I> for [T]>::index
             at /home/fred/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:15:9
   9: <alloc::vec::Vec<T,A> as core::ops::index::Index<I>>::index
             at /home/fred/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/vec/mod.rs:2427:9
  10: MFEKmath::variable_width_stroking::variable_width_stroke
             at /home/fred/.cargo/git/checkouts/math.rlib-d2c76c88b18fa5ee/2547be6/src/variable_width_stroking.rs:138:28
  11: MFEKglif::contour_operations::variablewidthstroke::<impl MFEKglif::contour_operations::ContourOperation for glifparser::glif::mfek::VWSContour>::build
             at src/contour_operations/variablewidthstroke.rs:16:26
  12: MFEKglif::contour_operations::build
             at src/contour_operations/mod.rs:49:20
  13: MFEKglif::editor::operations::<impl MFEKglif::editor::Editor>::rebuild
             at src/editor/operations.rs:30:36
  14: MFEKglif::main
             at src/main.rs:308:9
  15: core::ops::function::FnOnce::call_once
             at /home/fred/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  16: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /home/fred/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:125:18
  17: std::rt::lang_start::{{closure}}
             at /home/fred/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:49:18
  18: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/panicking.rs:379:40
      std::panicking::try
             at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/panicking.rs:343:19
      std::panic::catch_unwind
             at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/panic.rs:431:14
      std::rt::lang_start_internal
             at /rustc/79e50bf77928f374921a6bcafee3fcff1915f062/library/std/src/rt.rs:34:21
  19: std::rt::lang_start
             at /home/fred/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/rt.rs:48:5
  20: main
  21: __libc_start_main
  22: _start


shell returned 101
```

**Comment by ctrlcctrlv** [comment]
I solved this in fbda1bcf4af2a62e76cf97fb858b18a35621114a.

![image](https://user-images.githubusercontent.com/838783/150409292-02c841c1-a773-4960-9874-de48ae350f2b.png)
![image](https://user-images.githubusercontent.com/838783/150409333-7e5c6c51-0e7b-4840-a4ef-c75574dac8fb.png)
![image](https://user-images.githubusercontent.com/838783/150409354-d6cd8d2c-f67d-43fc-9588-dea94735260c.png)
